spring:
  profiles:
    active: test
---
spring:
  profiles: test
  application:
    name: trade-test
server:
  port: 8763
---
spring:
  profiles: prod
  application:
    name: trade-prod
server:
  port: 8773
