server:
  port: 8763
spring:
  profiles:
    active: dev
  application:
    name: trade-dev          			
------------------------
server:
  port: 8763
spring:
  profiles:
    active: pro
  application:
    name: trade-pro       			                      
