spring:
  profiles:
    active: dev
-----------------------
server:
  port: 8763
spring:
  profiles: dev
  application:
    name: trade-dev          			

server:
  port: 8773
spring:
  profiles: pro
  application:
    name: trade-pro       			                      
