spring:
  profiles:
    active: dev
-----------------------
spring:
  profiles: dev
  application:
    name: trade-dev          			
server:
  port: 8763
-----------------------
spring:
  profiles: pro
  application:
    name: trade-pro       			                      
server:
  port: 8773
